# Generated by Django 3.2.4 on 2021-07-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_customer',
            new_name='stripe_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
    ]
